services:
  redis:
    image: redis:latest
    container_name: redis-container
    hostname: host # 네트워크 내부에서의 호스트 이름
    ports:
      - '6379:6379'
    restart: always
    command: ['redis-server', '--requirepass', 'aaaa4321'] # 비밀번호 설정
    volumes:
      - redis_data:/data

volumes:
  redis_data:
